// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB43ZvKfN533eqOJ2rI2e9WZ2Le7HcXtUs',
    appId: '1:533865808336:android:56a607b5aaa524492179d5',
    messagingSenderId: '533865808336',
    projectId: 'nutrifit-2',
    authDomain: 'nutrifit-2.firebaseapp.com',
    storageBucket: 'nutrifit-2.firebasestorage.app',
    measurementId: 'G-47FJNLK4XZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuuuLtNbbGtTmkejOlMZzf6zy8O1QhWxI',
    appId: '1:533865808336:android:56a607b5aaa524492179d5',
    messagingSenderId: '533865808336',
    projectId: 'nutrifit-2',
    storageBucket: 'nutrifit-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIMKjcRmhTm1FKhDqcYnQNozE2v1TiYRQ',
    appId: '1:533865808336:android:56a607b5aaa524492179d5',
    messagingSenderId: '533865808336',
    projectId: 'nutrifit-2',
    storageBucket: 'nutrifit-2.firebasestorage.app',
    iosBundleId: 'com.nutrifit.sah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIMKjcRmhTm1FKhDqcYnQNozE2v1TiYRQ',
    appId: '1:533865808336:android:56a607b5aaa524492179d5',
    messagingSenderId: '533865808336',
    projectId: 'nutrifit-2',
    storageBucket: 'nutrifit-2.firebasestorage.app',
    iosBundleId: 'com.nutrifit.sah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB43ZvKfN533eqOJ2rI2e9WZ2Le7HcXtUs',
    appId: '1:533865808336:android:56a607b5aaa524492179d5',
    messagingSenderId: '533865808336',
    projectId: 'nutrifit-2',
    authDomain: 'nutrifit-2.firebaseapp.com',
    storageBucket: 'nutrifit-2.firebasestorage.app',
    measurementId: 'G-VWVJCM0HLC',
  );
}
